### ISSUE TITLE
face detection

### ISSUE THREAD

**Issue by MayYoY** [nxsEdson/CVD-Physiological-Measurement#11]
I would like to know how to get 81 landmarks from seetaface. It seems the open source detector only provides 5 landmarks detection.

**Comment by nxsEdson** [comment]
It seems that the SeetaFace Engine has become a commercial tool right now, you can use the OpenFace toolbox to get the 68 landmarks instead.

**Comment by nxsEdson** [comment]
> 
It seems that the SeetaFace Engine has become a commercial tool right now, you can use the OpenFace toolbox to get the 68 landmarks instead.
