### ISSUE TITLE
Pearson Correlration for PPG Evaluation

### ISSUE THREAD

**Issue by hoknshin** [nxsEdson/CVD-Physiological-Measurement#3]
Hi,
I have a question about your ECCV 2020 paper.
Could you clearfy the meaning of r value in Table 1?
Does the r value mean that P. Correlation between the average heart rate values? --> 1)
Or the average of P. Correlation between ppg waveforms for each video? --> 2)
Which one is usual evaluation metrics for ppg? (not training)

For example,
N = number of videos in Dataset
case 1) get average Heart Rate for each video -> calculate P. Corr. between avg HR prediction and groundtruth
case 2) calculate P. Corr using ppg wave form for each video -> get average for all videos in dataset

Thank you in advance.

**Comment by nxsEdson** [comment]
The calculation of the r value is for the first scenario: the average heart rate values.
